pipeline{
    agent any

    tools{
        maven "jenkins-mvn"
    }
    
    environment{
        binlocation='C:\\softinst\\apache\\tomcat\\bin\\startup.bat'
        webapplocation='C:\\softinst\\apache\\tomcat\\webapps\\'
        buildlocation='C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\DXC-pipeline-scm-multi\\mywebapp\\target\\mywebapp.war'
    }

    stages{

        stage('Git Checkout'){
            steps{

            git 'https://github.com/codewithz/dxc-web-app.git'
            }
        }

        stage('Maven Build'){
            steps{
            bat """
                cd mywebapp
                set JAVA_HOME=C:\\softinst\\java\\jdk8
                C:\\softinst\\apache\\maven\\bin\\mvn clean package
            """
            }
        }
    }
    

       post{
         
           success{
                
               bat """
                   copy %buildlocation% %webapplocation%
                   set JAVA_HOME=C:\\softinst\\java\\jdk8
                   set CATALINA_HOME=C:\\softinst\\apache\\tomcat
                   %binlocation%
               """
           }
       }    
}
