pipeline{

	agent any
	
	tools {
		maven 'jenkins-mvm'
	}
	
	stages{
		
		stage ('Build'){
			
			steps {
				
				git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
				
				bat 'mvn clean install'
			
			}
		}
	
	}
}
