pipeline{

	agent any
	
	tools {
		maven 'jenkins-mvn'
	}
	
	stages{
		
		stage ('Build'){
			
			steps {
				
				git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
				
			
				bat """
				
				set JAVA_HOME=C:\\softinst\\java\\jdk8
				
				C:\\softinst\\apache\\maven\\bin\\mvn clean test package
			
				"""
			}
		}
	
	}
	
	post{
	
		success{
			bat """
				
			set JAVA_HOME=C:\\softinst\\java\\jdk8
			
			C:\\softinst\\java\\jdk8\\bin\\java -jar C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\DXC-pipeline-scm-multi-1\\target\\my-app-1.0-SNAPSHOT.jar
			
			"""
		}
	}
}
